### ISSUE TITLE
"before all" hook error when running ./specs-docker.sh

### ISSUE THREAD

**Issue by jcummins54** [laardee/serverless-authentication-boilerplate#19]
Have followed README line by line. When running the tests I get the following errors:

  Setup specs
    1) "before all" hook

  Authentication
    Signin 
      2) should fail to return token for invalid provider

All the Authentication Providers error as well. Serverless 1.0.2 installed. OSX El Capitan. Docker 1.12.1

**Comment by laardee** [comment]
Ok, I see that the instructions how to run specs are not so good. Obviously you have ran `npm install` on project root (which was missing from instructions) because it would of fail before running nay tests. Do you have docker compose installed? You could check that `LOCAL_DDB_ENDPOINT` ip in specs-docker.sh is same than default docker machine ip by running `docker-machine ip default`. Can you share the error that it thows or least parts of it?

**Comment by jcummins54** [comment]
When I run `docker-machine ip default` it outputs `Host does not exist: "default"`. I'm new to docker so I may be missing something here. I ran `docker-compose up -d` from the root of the project.

**Comment by jcummins54** [comment]
This is resolved. On my system it was just localhost.
